### ISSUE TITLE
An  installation problem about 'speechmetrics' repository

### ISSUE THREAD

**Issue by Xuzezheng** [aliutkus/speechmetrics#1]
Hi,I failed to install your speechmetrics on windows neither python3 nor python2 yesterday，and I also tried on ubuntu but failed again.Could you tell me whats the problem and how I can solve it?Thanks!
there are no issues button in your  'speechmetrics' repository ,so I raise the question there

![error](https://user-images.githubusercontent.com/48405828/68728453-5db3ff00-0602-11ea-8477-0471d5dc147d.png)

**Comment by Xuzezheng** [comment]
thanks for your reply，and there were the problems on my friend‘s ubuntu 
![1](https://user-images.githubusercontent.com/48405828/68772934-9d600280-0665-11ea-84ac-117319de99fb.png)
this error was on py3 mentioned above，
![2](https://user-images.githubusercontent.com/48405828/68773105-edd76000-0665-11ea-98c5-95ec9a3d6537.jpg)
and this was on py2.

**Comment by aliutkus** [comment]
* for py3: could you please upgrade your pip and try again ?

* concerning py2, please note that `speechmetrics` is only for python 3. 
In anycase, your problem doesn't seem related to that particular repository.
please check:
https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls

**Comment by Xuzezheng** [comment]
Thanks for your advice,I would try it 

Best
