### ISSUE TITLE
Is this going to depend on `bsseval`

### ISSUE THREAD

**Issue by mpariente** [aliutkus/speechmetrics#2]
Thanks for the wrapper, it's a nice idea ! 
Is `speechmetrics` going to depend on `bsseval` once it is done?
Which would also mean that `speechmetrics` will include SI-SDR? That would be really practical to share the same metrics in the community.

**Comment by aliutkus** [comment]
hi, thanks actually to you for writing some of these!
sure I would be glad to include whichever metric gets available that could be of interest.
also, feel free to PR if you find one that you want to include

**Comment by mpariente** [comment]
Thanks for the quick answer ! Noted :-)

**Comment by aliutkus** [comment]
@mpariente I decided to add SI-SDR directly, for convenience,

could you please check [this](https://github.com/aliutkus/speechmetrics/commit/702d46b5ee1aad42b0ac1e53ea81a7faadb24682) out ?
