### ISSUE TITLE
Failed to install speechmetrics following steps in Installation section

### ISSUE THREAD

**Issue by BilalDendani** [aliutkus/speechmetrics#4]
Hello everyone, 
I am following steps on the README to install speechmetrics however I am facing the following errors:
(base) [bilal@Fedora ~]$ pip install git+https://github.com/aliutkus/speechmetrics#egg=speechmetrics[cpu]
Collecting speechmetrics[cpu] from git+https://github.com/aliutkus/speechmetrics#egg=speechmetrics[cpu]
  Cloning https://github.com/aliutkus/speechmetrics to /tmp/pip-install-3ibjsrho/speechmetrics
  Running command git clone -q https://github.com/aliutkus/speechmetrics /tmp/pip-install-3ibjsrho/speechmetrics
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
ERROR: Command "git clone -q https://github.com/aliutkus/speechmetrics /tmp/pip-install-3ibjsrho/speechmetrics" failed with error code 128 in None

**Comment by aliutkus** [comment]
it looks like a transfer problem

please try the latest pip

**Comment by BilalDendani** [comment]
Thank you @aliutkus .
Problem solved when upgrading to the latest version of pip 
pip install --upgrade pip 
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 23kB/s 
Installing collected packages: pip
  Found existing installation: pip 19.1.1
    Uninstalling pip-19.1.1:
      Successfully uninstalled pip-19.1.1
Successfully installed pip-19.3.1

**Comment by aliutkus** [comment]
perfect, closing the issue
