### ISSUE TITLE
Why is the MOSNET value not 5 when two files are the same

### ISSUE THREAD

**Issue by a897456** [aliutkus/speechmetrics#40]
I pointed both the reference file and the evaluation file to the same audio file and found that the MOSNET value is 2.6, which is unscientific, what went wrong?
![image](https://github.com/aliutkus/speechmetrics/assets/28752526/49e20efd-e0fb-4c2c-a57f-96e980e1ffdb)

**Comment by aliutkus** [comment]
Hi, please raise an issue on the mosnet repo and not here, since I am just calling the code that was designed there: https://github.com/lochenchou/MOSNet !
thanks
